// 도/시 데이터
export const PROVINCES = [
  { id: 1, key: 'seoul', name: '서울특별시' },
  { id: 2, key: 'busan', name: '부산광역시' },
  { id: 3, key: 'daegu', name: '대구광역시' },
  { id: 4, key: 'incheon', name: '인천광역시' },
  { id: 5, key: 'gwangju', name: '광주광역시' },
  { id: 6, key: 'daejeon', name: '대전광역시' },
  { id: 7, key: 'ulsan', name: '울산광역시' },
  { id: 8, key: 'sejong', name: '세종특별자치시' },
  { id: 9, key: 'gyeonggi', name: '경기도' },
  { id: 10, key: 'gangwon', name: '강원도' },
  { id: 11, key: 'chungbuk', name: '충청북도' },
  { id: 12, key: 'chungnam', name: '충청남도' },
  { id: 13, key: 'jeonbuk', name: '전라북도' },
  { id: 14, key: 'jeonnam', name: '전라남도' },
  { id: 15, key: 'gyeongbuk', name: '경상북도' },
  { id: 16, key: 'gyeongnam', name: '경상남도' },
  { id: 17, key: 'jeju', name: '제주특별자치도' },
] as const

export const CITIES_LIST = [
  // 서울특별시 (provinceId: 1)
  { id: 101, key: 'gangnam', name: '강남구', provinceId: 1 },
  { id: 102, key: 'gangdong', name: '강동구', provinceId: 1 },
  { id: 103, key: 'gangbuk', name: '강북구', provinceId: 1 },
  { id: 104, key: 'gangseo', name: '강서구', provinceId: 1 },
  { id: 105, key: 'gwanak', name: '관악구', provinceId: 1 },
  { id: 106, key: 'gwangjin', name: '광진구', provinceId: 1 },
  { id: 107, key: 'guro', name: '구로구', provinceId: 1 },
  { id: 108, key: 'geumcheon', name: '금천구', provinceId: 1 },
  { id: 109, key: 'nowon', name: '노원구', provinceId: 1 },
  { id: 110, key: 'dobong', name: '도봉구', provinceId: 1 },
  { id: 111, key: 'dongdaemun', name: '동대문구', provinceId: 1 },
  { id: 112, key: 'dongjak', name: '동작구', provinceId: 1 },
  { id: 113, key: 'mapo', name: '마포구', provinceId: 1 },
  { id: 114, key: 'seodaemun', name: '서대문구', provinceId: 1 },
  { id: 115, key: 'seocho', name: '서초구', provinceId: 1 },
  { id: 116, key: 'seongdong', name: '성동구', provinceId: 1 },
  { id: 117, key: 'seongbuk', name: '성북구', provinceId: 1 },
  { id: 118, key: 'songpa', name: '송파구', provinceId: 1 },
  { id: 119, key: 'yangcheon', name: '양천구', provinceId: 1 },
  { id: 120, key: 'yeongdeungpo', name: '영등포구', provinceId: 1 },
  { id: 121, key: 'yongsan', name: '용산구', provinceId: 1 },
  { id: 122, key: 'eunpyeong', name: '은평구', provinceId: 1 },
  { id: 123, key: 'jongno', name: '종로구', provinceId: 1 },
  { id: 124, key: 'jung', name: '중구', provinceId: 1 },
  { id: 125, key: 'jungnang', name: '중랑구', provinceId: 1 },

  // 부산광역시 (provinceId: 2)
  { id: 201, key: 'gangseo', name: '강서구', provinceId: 2 },
  { id: 202, key: 'geumjeong', name: '금정구', provinceId: 2 },
  { id: 203, key: 'nam', name: '남구', provinceId: 2 },
  { id: 204, key: 'dong', name: '동구', provinceId: 2 },
  { id: 205, key: 'dongnae', name: '동래구', provinceId: 2 },
  { id: 206, key: 'busanjin', name: '부산진구', provinceId: 2 },
  { id: 207, key: 'buk', name: '북구', provinceId: 2 },
  { id: 208, key: 'sasang', name: '사상구', provinceId: 2 },
  { id: 209, key: 'saha', name: '사하구', provinceId: 2 },
  { id: 210, key: 'seo', name: '서구', provinceId: 2 },
  { id: 211, key: 'suyeong', name: '수영구', provinceId: 2 },
  { id: 212, key: 'yeonje', name: '연제구', provinceId: 2 },
  { id: 213, key: 'yeongdo', name: '영도구', provinceId: 2 },
  { id: 214, key: 'jung_busan', name: '중구', provinceId: 2 },
  { id: 215, key: 'haeundae', name: '해운대구', provinceId: 2 },
  { id: 216, key: 'gijang', name: '기장군', provinceId: 2 },

  // 대구광역시 (provinceId: 3)
  { id: 301, key: 'nam_daegu', name: '남구', provinceId: 3 },
  { id: 302, key: 'dalseo', name: '달서구', provinceId: 3 },
  { id: 303, key: 'dalseong', name: '달성군', provinceId: 3 },
  { id: 304, key: 'dong_daegu', name: '동구', provinceId: 3 },
  { id: 305, key: 'buk_daegu', name: '북구', provinceId: 3 },
  { id: 306, key: 'seo_daegu', name: '서구', provinceId: 3 },
  { id: 307, key: 'suseong', name: '수성구', provinceId: 3 },
  { id: 308, key: 'jung_daegu', name: '중구', provinceId: 3 },

  // 인천광역시 (provinceId: 4)
  { id: 401, key: 'gyeyang', name: '계양구', provinceId: 4 },
  { id: 402, key: 'namdong', name: '남동구', provinceId: 4 },
  { id: 403, key: 'dong_incheon', name: '동구', provinceId: 4 },
  { id: 404, key: 'michuhol', name: '미추홀구', provinceId: 4 },
  { id: 405, key: 'bupyeong', name: '부평구', provinceId: 4 },
  { id: 406, key: 'seo_incheon', name: '서구', provinceId: 4 },
  { id: 407, key: 'yeonsu', name: '연수구', provinceId: 4 },
  { id: 408, key: 'jung_incheon', name: '중구', provinceId: 4 },
  { id: 409, key: 'ganghwa', name: '강화군', provinceId: 4 },
  { id: 410, key: 'ongjin', name: '옹진군', provinceId: 4 },

  // 광주광역시 (provinceId: 5)
  { id: 501, key: 'gwangsan', name: '광산구', provinceId: 5 },
  { id: 502, key: 'nam_gwangju', name: '남구', provinceId: 5 },
  { id: 503, key: 'dong_gwangju', name: '동구', provinceId: 5 },
  { id: 504, key: 'buk_gwangju', name: '북구', provinceId: 5 },
  { id: 505, key: 'seo_gwangju', name: '서구', provinceId: 5 },

  // 대전광역시 (provinceId: 6)
  { id: 601, key: 'daedeok', name: '대덕구', provinceId: 6 },
  { id: 602, key: 'dong_daejeon', name: '동구', provinceId: 6 },
  { id: 603, key: 'seo_daejeon', name: '서구', provinceId: 6 },
  { id: 604, key: 'yuseong', name: '유성구', provinceId: 6 },
  { id: 605, key: 'jung_daejeon', name: '중구', provinceId: 6 },

  // 울산광역시 (provinceId: 7)
  { id: 701, key: 'nam_ulsan', name: '남구', provinceId: 7 },
  { id: 702, key: 'dong_ulsan', name: '동구', provinceId: 7 },
  { id: 703, key: 'buk_ulsan', name: '북구', provinceId: 7 },
  { id: 704, key: 'jung_ulsan', name: '중구', provinceId: 7 },
  { id: 705, key: 'ulju', name: '울주군', provinceId: 7 },

  // 세종특별자치시 (provinceId: 8)
  { id: 801, key: 'sejong_city', name: '세종시', provinceId: 8 },

  // 경기도 (provinceId: 9)
  { id: 901, key: 'goyang', name: '고양시', provinceId: 9 },
  { id: 902, key: 'gwacheon', name: '과천시', provinceId: 9 },
  { id: 903, key: 'gwangmyeong', name: '광명시', provinceId: 9 },
  { id: 904, key: 'gwangju_gy', name: '광주시', provinceId: 9 },
  { id: 905, key: 'guri', name: '구리시', provinceId: 9 },
  { id: 906, key: 'gunpo', name: '군포시', provinceId: 9 },
  { id: 907, key: 'gimpo', name: '김포시', provinceId: 9 },
  { id: 908, key: 'namyangju', name: '남양주시', provinceId: 9 },
  { id: 909, key: 'dongducheon', name: '동두천시', provinceId: 9 },
  { id: 910, key: 'bucheon', name: '부천시', provinceId: 9 },
  { id: 911, key: 'seongnam', name: '성남시', provinceId: 9 },
  { id: 912, key: 'suwon', name: '수원시', provinceId: 9 },
  { id: 913, key: 'siheung', name: '시흥시', provinceId: 9 },
  { id: 914, key: 'ansan', name: '안산시', provinceId: 9 },
  { id: 915, key: 'anseong', name: '안성시', provinceId: 9 },
  { id: 916, key: 'anyang', name: '안양시', provinceId: 9 },
  { id: 917, key: 'yangju', name: '양주시', provinceId: 9 },
  { id: 918, key: 'osan', name: '오산시', provinceId: 9 },
  { id: 919, key: 'yongin', name: '용인시', provinceId: 9 },
  { id: 920, key: 'uiwang', name: '의왕시', provinceId: 9 },
  { id: 921, key: 'uijeongbu', name: '의정부시', provinceId: 9 },
  { id: 922, key: 'icheon', name: '이천시', provinceId: 9 },
  { id: 923, key: 'paju', name: '파주시', provinceId: 9 },
  { id: 924, key: 'pyeongtaek', name: '평택시', provinceId: 9 },
  { id: 925, key: 'pocheon', name: '포천시', provinceId: 9 },
  { id: 926, key: 'hanam', name: '하남시', provinceId: 9 },
  { id: 927, key: 'hwaseong', name: '화성시', provinceId: 9 },
  { id: 928, key: 'gapyeong', name: '가평군', provinceId: 9 },
  { id: 929, key: 'yangpyeong', name: '양평군', provinceId: 9 },
  { id: 930, key: 'yeoncheon', name: '연천군', provinceId: 9 },

  // 강원도 (provinceId: 10)
  { id: 1001, key: 'gangneung', name: '강릉시', provinceId: 10 },
  { id: 1002, key: 'donghae', name: '동해시', provinceId: 10 },
  { id: 1003, key: 'samcheok', name: '삼척시', provinceId: 10 },
  { id: 1004, key: 'sokcho', name: '속초시', provinceId: 10 },
  { id: 1005, key: 'wonju', name: '원주시', provinceId: 10 },
  { id: 1006, key: 'chuncheon', name: '춘천시', provinceId: 10 },
  { id: 1007, key: 'taebaek', name: '태백시', provinceId: 10 },
  { id: 1008, key: 'goseong_gw', name: '고성군', provinceId: 10 },
  { id: 1009, key: 'yanggu', name: '양구군', provinceId: 10 },
  { id: 1010, key: 'yangyang', name: '양양군', provinceId: 10 },
  { id: 1011, key: 'yeongwol', name: '영월군', provinceId: 10 },
  { id: 1012, key: 'inje', name: '인제군', provinceId: 10 },
  { id: 1013, key: 'jeongseon', name: '정선군', provinceId: 10 },
  { id: 1014, key: 'cheorwon', name: '철원군', provinceId: 10 },
  { id: 1015, key: 'pyeongchang', name: '평창군', provinceId: 10 },
  { id: 1016, key: 'hongcheon', name: '홍천군', provinceId: 10 },
  { id: 1017, key: 'hwacheon', name: '화천군', provinceId: 10 },
  { id: 1018, key: 'hoengseong', name: '횡성군', provinceId: 10 },

  // 충청북도 (provinceId: 11)
  { id: 1101, key: 'jecheon', name: '제천시', provinceId: 11 },
  { id: 1102, key: 'cheongju', name: '청주시', provinceId: 11 },
  { id: 1103, key: 'chungju', name: '충주시', provinceId: 11 },
  { id: 1104, key: 'goesan', name: '괴산군', provinceId: 11 },
  { id: 1105, key: 'danyang', name: '단양군', provinceId: 11 },
  { id: 1106, key: 'boeun', name: '보은군', provinceId: 11 },
  { id: 1107, key: 'yeongdong', name: '영동군', provinceId: 11 },
  { id: 1108, key: 'okcheon', name: '옥천군', provinceId: 11 },
  { id: 1109, key: 'eumseong', name: '음성군', provinceId: 11 },
  { id: 1110, key: 'jeungpyeong', name: '증평군', provinceId: 11 },
  { id: 1111, key: 'jincheon', name: '진천군', provinceId: 11 },

  // 충청남도 (provinceId: 12)
  { id: 1201, key: 'gyeryong', name: '계룡시', provinceId: 12 },
  { id: 1202, key: 'gongju', name: '공주시', provinceId: 12 },
  { id: 1203, key: 'nonsan', name: '논산시', provinceId: 12 },
  { id: 1204, key: 'dangjin', name: '당진시', provinceId: 12 },
  { id: 1205, key: 'boryeong', name: '보령시', provinceId: 12 },
  { id: 1206, key: 'seosan', name: '서산시', provinceId: 12 },
  { id: 1207, key: 'asan', name: '아산시', provinceId: 12 },
  { id: 1208, key: 'cheonan', name: '천안시', provinceId: 12 },
  { id: 1209, key: 'geumsan', name: '금산군', provinceId: 12 },
  { id: 1210, key: 'buyeo', name: '부여군', provinceId: 12 },
  { id: 1211, key: 'seocheon', name: '서천군', provinceId: 12 },
  { id: 1212, key: 'yesan', name: '예산군', provinceId: 12 },
  { id: 1213, key: 'cheongyang', name: '청양군', provinceId: 12 },
  { id: 1214, key: 'taean', name: '태안군', provinceId: 12 },
  { id: 1215, key: 'hongseong', name: '홍성군', provinceId: 12 },

  // 전라북도 (provinceId: 13)
  { id: 1301, key: 'gunsan', name: '군산시', provinceId: 13 },
  { id: 1302, key: 'gimje', name: '김제시', provinceId: 13 },
  { id: 1303, key: 'namwon', name: '남원시', provinceId: 13 },
  { id: 1304, key: 'iksan', name: '익산시', provinceId: 13 },
  { id: 1305, key: 'jeonju', name: '전주시', provinceId: 13 },
  { id: 1306, key: 'jeongeup', name: '정읍시', provinceId: 13 },
  { id: 1307, key: 'gochang', name: '고창군', provinceId: 13 },
  { id: 1308, key: 'muju', name: '무주군', provinceId: 13 },
  { id: 1309, key: 'buan', name: '부안군', provinceId: 13 },
  { id: 1310, key: 'sunchang', name: '순창군', provinceId: 13 },
  { id: 1311, key: 'wanju', name: '완주군', provinceId: 13 },
  { id: 1312, key: 'imsil', name: '임실군', provinceId: 13 },
  { id: 1313, key: 'jangsu', name: '장수군', provinceId: 13 },
  { id: 1314, key: 'jinan', name: '진안군', provinceId: 13 },

  // 전라남도 (provinceId: 14)
  { id: 1401, key: 'gwangyang', name: '광양시', provinceId: 14 },
  { id: 1402, key: 'naju', name: '나주시', provinceId: 14 },
  { id: 1403, key: 'mokpo', name: '목포시', provinceId: 14 },
  { id: 1404, key: 'suncheon', name: '순천시', provinceId: 14 },
  { id: 1405, key: 'yeosu', name: '여수시', provinceId: 14 },
  { id: 1406, key: 'gangjin', name: '강진군', provinceId: 14 },
  { id: 1407, key: 'goheung', name: '고흥군', provinceId: 14 },
  { id: 1408, key: 'gokseong', name: '곡성군', provinceId: 14 },
  { id: 1409, key: 'gurye', name: '구례군', provinceId: 14 },
  { id: 1410, key: 'damyang', name: '담양군', provinceId: 14 },
  { id: 1411, key: 'muan', name: '무안군', provinceId: 14 },
  { id: 1412, key: 'boseong', name: '보성군', provinceId: 14 },
  { id: 1413, key: 'sinan', name: '신안군', provinceId: 14 },
  { id: 1414, key: 'yeonggwang', name: '영광군', provinceId: 14 },
  { id: 1415, key: 'yeongam', name: '영암군', provinceId: 14 },
  { id: 1416, key: 'wando', name: '완도군', provinceId: 14 },
  { id: 1417, key: 'jangseong', name: '장성군', provinceId: 14 },
  { id: 1418, key: 'jangheung', name: '장흥군', provinceId: 14 },
  { id: 1419, key: 'jindo', name: '진도군', provinceId: 14 },
  { id: 1420, key: 'hampyeong', name: '함평군', provinceId: 14 },
  { id: 1421, key: 'haenam', name: '해남군', provinceId: 14 },
  { id: 1422, key: 'hwasun', name: '화순군', provinceId: 14 },

  // 경상북도 (provinceId: 15)
  { id: 1501, key: 'gyeongsan', name: '경산시', provinceId: 15 },
  { id: 1502, key: 'gyeongju', name: '경주시', provinceId: 15 },
  { id: 1503, key: 'gumi', name: '구미시', provinceId: 15 },
  { id: 1504, key: 'gimcheon', name: '김천시', provinceId: 15 },
  { id: 1505, key: 'mungyeong', name: '문경시', provinceId: 15 },
  { id: 1506, key: 'sangju', name: '상주시', provinceId: 15 },
  { id: 1507, key: 'andong', name: '안동시', provinceId: 15 },
  { id: 1508, key: 'yeongju', name: '영주시', provinceId: 15 },
  { id: 1509, key: 'yeongcheon', name: '영천시', provinceId: 15 },
  { id: 1510, key: 'pohang', name: '포항시', provinceId: 15 },
  { id: 1511, key: 'goryeong', name: '고령군', provinceId: 15 },
  { id: 1512, key: 'gunwi', name: '군위군', provinceId: 15 },
  { id: 1513, key: 'bonghwa', name: '봉화군', provinceId: 15 },
  { id: 1514, key: 'seongju', name: '성주군', provinceId: 15 },
  { id: 1515, key: 'yeongdeok', name: '영덕군', provinceId: 15 },
  { id: 1516, key: 'yeongyang', name: '영양군', provinceId: 15 },
  { id: 1517, key: 'yecheon', name: '예천군', provinceId: 15 },
  { id: 1518, key: 'ulleung', name: '울릉군', provinceId: 15 },
  { id: 1519, key: 'uljin', name: '울진군', provinceId: 15 },
  { id: 1520, key: 'uiseong', name: '의성군', provinceId: 15 },
  { id: 1521, key: 'cheongdo', name: '청도군', provinceId: 15 },
  { id: 1522, key: 'cheongsong', name: '청송군', provinceId: 15 },
  { id: 1523, key: 'chilgok', name: '칠곡군', provinceId: 15 },

  // 경상남도 (provinceId: 16)
  { id: 1601, key: 'geoje', name: '거제시', provinceId: 16 },
  { id: 1602, key: 'gimhae', name: '김해시', provinceId: 16 },
  { id: 1603, key: 'miryang', name: '밀양시', provinceId: 16 },
  { id: 1604, key: 'sacheon', name: '사천시', provinceId: 16 },
  { id: 1605, key: 'yangsan', name: '양산시', provinceId: 16 },
  { id: 1606, key: 'jinju', name: '진주시', provinceId: 16 },
  { id: 1607, key: 'changwon', name: '창원시', provinceId: 16 },
  { id: 1608, key: 'tongyeong', name: '통영시', provinceId: 16 },
  { id: 1609, key: 'geochang', name: '거창군', provinceId: 16 },
  { id: 1610, key: 'goseong_gn', name: '고성군', provinceId: 16 },
  { id: 1611, key: 'namhae', name: '남해군', provinceId: 16 },
  { id: 1612, key: 'sancheong', name: '산청군', provinceId: 16 },
  { id: 1613, key: 'uiryeong', name: '의령군', provinceId: 16 },
  { id: 1614, key: 'changnyeong', name: '창녕군', provinceId: 16 },
  { id: 1615, key: 'hadong', name: '하동군', provinceId: 16 },
  { id: 1616, key: 'haman', name: '함안군', provinceId: 16 },
  { id: 1617, key: 'hamyang', name: '함양군', provinceId: 16 },
  { id: 1618, key: 'hapcheon', name: '합천군', provinceId: 16 },

  // 제주특별자치도 (provinceId: 17)
  { id: 1701, key: 'jeju', name: '제주시', provinceId: 17 },
  { id: 1702, key: 'seogwipo', name: '서귀포시', provinceId: 17 },
] as const
