name: Backend Test

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
      KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
      KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      H2_URL: ${{ secrets.H2_URL }}
      DEV_DB_DRIVER: ${{ secrets.DEV_DB_DRIVER }}
      H2_USERNAME: ${{ secrets.H2_USERNAME }}
      H2_PASSWORD: ${{ secrets.H2_PASSWORD }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_AUDIO_FOLDER: ${{ secrets.AWS_S3_AUDIO_FOLDER }}

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run unit tests
        run: SPRING_PROFILES_ACTIVE=dev ./gradlew test

      - name: Run build
        run: SPRING_PROFILES_ACTIVE=dev ./gradlew build

      - name: Check code style
        run: ./gradlew check
